### ISSUE TITLE
Doesn't work on Build.VERSION_CODES.Q

### ISSUE THREAD

**Issue by iamshouvikmitra** [kashifo/android-folder-picker-library#14]
No folders or file shows up on API Level 29.
```

2020-03-12 22:52:41.448 28903-28903/in.navigus.phonesync W/System.err: java.lang.NullPointerException: Attempt to get length of null array
2020-03-12 22:52:41.448 28903-28903/in.navigus.phonesync W/System.err:     at lib.folderpicker.FolderPicker.loadLists(FolderPicker.java:107)
2020-03-12 22:52:41.449 28903-28903/in.navigus.phonesync W/System.err:     at lib.folderpicker.FolderPicker.goBack(FolderPicker.java:192)
2020-03-12 22:52:41.449 28903-28903/in.navigus.phonesync W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-03-12 22:52:41.449 28903-28903/in.navigus.phonesync W/System.err:     at android.view.View$DeclaredOnClickListener.onClick(View.java:6028)
2020-03-12 22:52:41.449 28903-28903/in.navigus.phonesync W/System.err:     at android.view.View.performClick(View.java:7192)
2020-03-12 22:52:41.449 28903-28903/in.navigus.phonesync W/System.err:     at android.view.View.performClickInternal(View.java:7166)
2020-03-12 22:52:41.449 28903-28903/in.navigus.phonesync W/System.err:     at android.view.View.access$3500(View.java:824)
2020-03-12 22:52:41.449 28903-28903/in.navigus.phonesync W/System.err:     at android.view.View$PerformClick.run(View.java:27592)
2020-03-12 22:52:41.449 28903-28903/in.navigus.phonesync W/System.err:     at android.os.Handler.handleCallback(Handler.java:888)
2020-03-12 22:52:41.449 28903-28903/in.navigus.phonesync W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:100)
2020-03-12 22:52:41.449 28903-28903/in.navigus.phonesync W/System.err:     at android.os.Looper.loop(Looper.java:213)
2020-03-12 22:52:41.449 28903-28903/in.navigus.phonesync W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:8178)
2020-03-12 22:52:41.449 28903-28903/in.navigus.phonesync W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-03-12 22:52:41.449 28903-28903/in.navigus.phonesync W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
2020-03-12 22:52:41.449 28903-28903/in.navigus.phonesync W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
```

**Comment by kashifo** [comment]
Thanks, will add support for API level 29.
